Models/ErrorViewModel.cs
using System;

namespace NotiUcse.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/NoticiaModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace NotiUcse.Models
{
    public class NoticiaModel
    {
        public int Id { get; set; }
        public string Titulo { get; set; }

        [DataType(DataType.Date)]
        public DateTime FechaPublicacion { get; set; }
        public string Seccion { get; set; }
        public string Cuerpo { get; set; }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NotiUcse.Models;

namespace NotiUcse.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Text.Encodings.Web;

namespace NotiUcse.Controllers
{
    public class NewsController : Controller
    {
        // 
        // GET: /News/

        public IActionResult Index()
        {
            return View();
        }

        // 
        // GET: /News/Noticias

        public string Noticias()
        {
            return "Un día como hoy (10/08) pero en 2010 en la Antártida se registra la temperatura más baja de la historia de -93,2 °C.";
        }

        public IActionResult NoticiasPorAnio(int id)
        {
            ViewData["TextoNoticia"] = String.Format("Un día como hoy (10/08) pero en {0} en la Antártida se registra la temperatura más baja de la historia de -93,2 °C.", id);

            return View();
        }
    }
}

Controllers/NoticiasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NotiUcse.Models;

namespace NotiUcse.Controllers
{
    public class NoticiasController : Controller
    {
        private readonly MvcNoticiasContext _context;

        public NoticiasController(MvcNoticiasContext context)
        {
            _context = context;
        }

        // GET: Noticias
        public async Task<IActionResult> Index()
        {
            return View(await _context.NoticiaModel.ToListAsync());
        }

        // GET: Noticias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var noticiaModel = await _context.NoticiaModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (noticiaModel == null)
            {
                return NotFound();
            }

            return View(noticiaModel);
        }

        // GET: Noticias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Noticias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,FechaPublicacion,Seccion,Cuerpo")] NoticiaModel noticiaModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(noticiaModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(noticiaModel);
        }

        // GET: Noticias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var noticiaModel = await _context.NoticiaModel.FindAsync(id);
            if (noticiaModel == null)
            {
                return NotFound();
            }
            return View(noticiaModel);
        }

        // POST: Noticias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,FechaPublicacion,Seccion,Cuerpo")] NoticiaModel noticiaModel)
        {
            if (id != noticiaModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(noticiaModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NoticiaModelExists(noticiaModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(noticiaModel);
        }

        // GET: Noticias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var noticiaModel = await _context.NoticiaModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (noticiaModel == null)
            {
                return NotFound();
            }

            return View(noticiaModel);
        }

        // POST: Noticias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var noticiaModel = await _context.NoticiaModel.FindAsync(id);
            _context.NoticiaModel.Remove(noticiaModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoticiaModelExists(int id)
        {
            return _context.NoticiaModel.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/News/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>Posible listado de noticias ...!</p>

Views/News/NoticiasPorAnio.cshtml
<h2>Bienvenido !</h2>

<p>@ViewData["TextoNoticia"]</p>

Views/Noticias/Create.cshtml
@model NotiUcse.Models.NoticiaModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>NoticiaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPublicacion" class="control-label"></label>
                <input asp-for="FechaPublicacion" class="form-control" />
                <span asp-validation-for="FechaPublicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seccion" class="control-label"></label>
                <input asp-for="Seccion" class="form-control" />
                <span asp-validation-for="Seccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuerpo" class="control-label"></label>
                <input asp-for="Cuerpo" class="form-control" />
                <span asp-validation-for="Cuerpo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Noticias/Delete.cshtml
@model NotiUcse.Models.NoticiaModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NoticiaModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPublicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPublicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuerpo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuerpo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Noticias/Details.cshtml
@model NotiUcse.Models.NoticiaModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>NoticiaModel</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPublicacion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPublicacion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Seccion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Seccion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cuerpo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cuerpo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Noticias/Edit.cshtml
@model NotiUcse.Models.NoticiaModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>NoticiaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPublicacion" class="control-label"></label>
                <input asp-for="FechaPublicacion" class="form-control" />
                <span asp-validation-for="FechaPublicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Seccion" class="control-label"></label>
                <input asp-for="Seccion" class="form-control" />
                <span asp-validation-for="Seccion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cuerpo" class="control-label"></label>
                <input asp-for="Cuerpo" class="form-control" />
                <span asp-validation-for="Cuerpo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Noticias/Index.cshtml
@model IEnumerable<NotiUcse.Models.NoticiaModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaPublicacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seccion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cuerpo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPublicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Seccion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cuerpo)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NotiUcse</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bienvenidos a NotiUcse!</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <partial name="_LoginPartial" /> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">News</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NotiUcse - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>